name: material_symbols_icons_cli
description: CLI tool to install fonts for the material_symbols_icons package.
version: 1.0.0
homepage: https://github.com/timmaffett/material_symbols_icons
repository: https://github.com/timmaffett/material_symbols_icons
#publish_to: 'none' # Uncomment to prevent accidental publishing
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.6.0
  path: ^1.9.0
  chalkdart: ^3.0.4
  glob: ^2.1.2
  material_symbols_icons: ">=4.0.0 <7.0.0"

executables:
  install_material_symbols_icons_fonts:
