name: example_using_material_symbols_icons 
description: Example package using pub.dev/packages/material_symbols_icons package.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.5
  material_symbols_icons:
    path: ../
  device_preview: ^1.1.0    # required only for virtual device screen testing
  splittable_flexible_row: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
