name: material_symbols_icons
description: Full flutter support for latest Google Material Symbols Icons.
version: 4.2801.4
homepage: https://github.com/timmaffett/material_symbols_icons
screenshots:
  - description: 'example flutter material symbols icon browser'
    path: media/example.png
  - description: 'google material symbols icon browser'
    path: media/google_icon_fonts.png

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  args: ^2.6.0
  path: ^1.9.1
  chalkdart: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  fonts:
    - family: MaterialSymbolsOutlined
      fonts:
       - asset: lib/fonts/MaterialSymbolsOutlined.ttf
       
    - family: MaterialSymbolsRounded
      fonts:
       - asset: lib/fonts/MaterialSymbolsRounded.ttf
       
    - family: MaterialSymbolsSharp
      fonts:
       - asset: lib/fonts/MaterialSymbolsSharp.ttf
    
executables:
  install_material_symbols_icons_fonts:

